source 'https://github.com/appunite/cocoapods-private.git'
source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'AUMediaNormalizer.xcodeproj'

platform :ios, '7.0'
inhibit_all_warnings!

pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDAVAssetExportSession', git: 'https://github.com/appunite/SDAVAssetExportSession.git'
#pod 'NYXImagesKit'
#pod 'Mantle', '~> 1.4.1'

target 'AUMediaNormalizer_Example', :exclusive => true do
  pod "AUMediaNormalizer", :path => "../"
end

target 'AUMediaNormalizer_Tests', :exclusive => true do
  pod "AUMediaNormalizer", :path => "../"

end
